### ISSUE TITLE
Animals attached to consumers are shown to browse

### ISSUE THREAD

**Issue by mocoatsu** [mocoatsu/feed-box#7]
## Overview
You can see animal attached to consumers on browser.  

## TODO
- [ ] consumers can connect to browsers using Websocket. 
- [ ] Animals can be see on browsers 
- [ ] When animals be full, animals can be switch to new ones.
